### ISSUE TITLE
Allow Form Data based Post

### ISSUE THREAD

**Issue by DronRathore** [DronRathore/safedelivr#6]
Currently the platform uses url-encoded post data params, to enable Email attachments we would need to support form-data boundary based requests.
Depends: DronRathore/goexpress#19

**Comment by akki91** [comment]
@DronRathore sending all sort of attachment .. not only pdf

**Comment by DronRathore** [comment]
Yes the form-data mimeReader will parse all the files attached within a request so we can attach all of them in our request. See API of goexpress [here](https://github.com/DronRathore/goexpress#form-data-post).

However I am still wondering if to rate limit the attachment size or not, [RFC](http://www.ietf.org/rfc/rfc2821.txt) doesn't promote this but all the email service providers have their own rate limits, saving an attachment on the server end can be done in 2 ways:
- Save in cassandra (blob)
- Save as local file/remote file and save the path in cassandra

In a distributed system 1st approach looks promising but cassandra doesn't scale for large file sizes as cassandra doesn't have streaming capabilities(thrift api, duuh), even a 10MB+ file can have significant hit on the system perfs(Gmail supports upto 25Mb file sizes), however we can chunk the whole file into multiple parts and than save them into the DB and then collect all the chunks while dispatching it.

2nd approach looks good but fails in a distributed system, we would need a distribute file system to handle that or a central server or we can do it by uploading it to amazon s3 but that would add another integration layer also amazon requires the file to be uploaded in chunks for large sizes. So we can have similar implementation with s3.

I think we can add both the options and let the user choose which one they want at boot time. Users with low disk or infra capabilities can use amazon s3 option.

In any case for a single node server saving file locally can always work.
So should I implement all 3 options? Or just the cassandra and s3 one?

**Comment by DronRathore** [comment]
Wallmart has been there and [done this](https://medium.com/walmartlabs/building-object-store-storing-images-in-cassandra-walmart-scale-a6b9c02af593) to save images in cassandra.

**Comment by DronRathore** [comment]
Closing this as goexpress has been updated, same been deployed too, will open another Issue to track implementation of attachment support.
